### ISSUE TITLE
We need to add a hash or something similar

### ISSUE THREAD

**Issue by NicoKos** [NicoKos/resume_connection#27]
We may want to detail how the server can have a guarantee that the client did not modify the BDP frame.

**Comment by gorryfair** [comment]
I think we should have an authentication mechanism, if the BDP-frame data from the server is passed to the client. That could be the encrypted BDP+a visible envelope, or a reading BDP and an authentication hash or similiar.

**Comment by NicoKos** [comment]
Or we should refer to the early_data extension protection mechanisms and avoid specifying something specific to this extension. what do you think?

**Comment by gorryfair** [comment]
I think it seems easy to just include a hash for integrity protection as a parameter. We could specify what - but maybe we do not need to, and it could be an opaque parameter that is generated and used only by the sender

**Comment by NicoKos** [comment]
This could indeed be something generated by the server and only seen by it. I think we could make it optional to include it in the extension but would not see much interest (the server would need to store it anyway,no?)

**Comment by gorryfair** [comment]
Let's see how this would work as a stateless server: The server takes it current state, and a local ID/encryption key that captures everything into one blob of cookie data. it then sends this to the client and deletes the data, it now does not need to track clients between connections. When the client resumes, the cookie is returned, the server verifies using it's private key and then can reconstruct any needed data. A nice feature is that the resuming server could be a different host - with access to the same server key (perhaps load-balanced in some way where the load balancer knows how to handle keys/IDs).  This resembles some uses of the CID or a TCP SYNC cookie. It transfers ownership off data and responsibility to the client.

**Comment by NicoKos** [comment]
If I understand correctly (and before proposing a PR), the idea would be to send, along with the transport parameters, a hash that the client can not read because it is protected by keys at the server side only (and compatible with a stateless server)?

**Comment by gorryfair** [comment]
Yes.
To be clear: I see the information in two parts 
(i)cc transport  params that are readable to the client (a receiver might wish to decide to increase offered flow credit; decide not to ask for a jump in cwnd - because it has recently requested a similar jump; knows the data it expects to receive would/ would not benefit from a jump; or configure the client request policy; decide to be ultra-private and compromise performance against more privacy; etc.)  
(ii) a token that when decrypted allows a server to confirm this is the same "server" and verifies that the params as supplied by the client are identical to what were previously sent. Only the server/set of servers need to, and can, decrypt this hash - and therefore a server can encode whatever it likes as a part of this hash in addition to the authentication itself, e.g. any additional information to help identify the "path" is the same.

**Comment by NicoKos** [comment]
Such as mentionned by Emile, we may want to also include the path token in the hash (and not only the transport parameters).

**Comment by gorryfair** [comment]
OK for me, to allow this - the hash to me is sender-side only.
