### ISSUE TITLE
How safe should be the retreat ?

### ISSUE THREAD

**Issue by NicoKos** [NicoKos/resume_connection#59]
From John Border: 
 Re Section 4.4 and Section 4.4.1…  I think half of the capacity should be a good choice (although I am still thinking about it).  (Might need to be variable based upon some to be defined criteria.)  But it probably needs to take into account the capacity when compared to the IW.

**Comment by gorryfair** [comment]
I wonder if we should discuss this and seek date with a delay to writin until we have fully thought-through the various scenarios, I expect that reducing to 2*IW when at least 2*IW ACKs were received will at least be sufficiently conservative - although likely one can be much more agrressive when the observed unvalidated loss rate (and hence adverse impact) is low.

**Comment by gorryfair** [comment]
I think we should leave this for wider discussion after this draft is adopted.

**Comment by gorryfair** [comment]
This is tricky to specify, but we now have words of discussion and some understanding of how this choice can play out. This is reflected in #86. 

Note also that if most of the packets were received, because the capacity was nearly correct, then fewer packets need recovered, and the sender ought to complete recovery rapidly - helped by RACK when used.

**Comment by gorryfair** [comment]
I think this is resolved in the latest rev.
